### ISSUE TITLE
Connection leak

### ISSUE THREAD

**Issue by Esmaay** [Mindgamesnl/storm#6]
As soon as I create 5 or more models, it will say that the connection is not available.
It will cause this error: https://haste.jazzkuh.com/utarurosij.apache, if I remove a random model, it will work again.

I thought that something might not be properly closed in the runMigrations method since it instantly errors if I have 6 or more models, if I have 5 it will give the error when I try to use the database, but it doesn't when I don't run the method.

My init method: https://haste.jazzkuh.com/uyepamurif.java

Models:
- https://haste.jazzkuh.com/ugubijizob.kotlin
- https://haste.jazzkuh.com/ijemufipos.less
- https://haste.jazzkuh.com/fagevojogo.less
- https://haste.jazzkuh.com/odawupaman.less
- https://haste.jazzkuh.com/peceruqaqo.less
- https://haste.jazzkuh.com/baqinituxo.typescript

**Comment by Jazzkuh** [comment]
I have tried this first with 4 models which worked as intended for me but then when i add a fifth i get the same error, so can reproduce^^

**Comment by Jazzkuh** [comment]
Alright, just had a look through storm, and it looks to me like storm doesn't close any queries, can you confirm @Mindgamesnl? I've also tested this with HikariCP and with the maximum pool size set to 100 instead of 10, and then it works as expected, so I would assume it has something to do with queries not closing properly.

**Comment by Mindgamesnl** [comment]
I'm using normal try with resources everywhere if I recall correctly, though it his behaviour does indeed suggest a fuckup.

I'll chip in and check later tonight.

**Comment by Mindgamesnl** [comment]
I found the problem, it's related to how table metadata is loaded upon startup which in turn is used to compare schema versions.
I'll push a fix by the end of the day.

**Comment by Mindgamesnl** [comment]
If either of you could confirm that this minor change fixes it, that'd be lovely.
I ran it against a local database, and it seems to do the job.

If you're using jitpack, then just request build `1.2.6`

**Comment by Esmaay** [comment]
Yes, this has fixed the issue! Thanks!

**Comment by Jazzkuh** [comment]
Can confirm, works! Thank you.
